version: '3.8'
services:
  streamer:
    build:
      context: ./dataStreamer
    ports:
      - 7474:7474
    restart: always
    networks:
      - default
  aggregator:
    build:
      context: ./dailyAggregator
    links:
      - streamer
    environment:
      - STREAMER_ADDR=streamer
      - RABBITMQ_SERVER_ADDR=host.docker.internal
    restart: always
    networks:
      - default
  processor:
    build:
      context: ./dataProcessingService
    environment:
      - RABBITMQ_SERVER_ADDR=host.docker.internal
      - BRAZIL_API_ADDR=brazil_api
    links:
      - brazil_api
    ports:
      - 9090:9090
    restart: always
    networks:
      - default
  brazil_api:
    build:
      context: ./brazil-api
    ports:
      - 8080:8080
    restart: always
    networks:
      - default
networks:
  default:
