version: '3.8'
services:
  data-streamer:
    build:
      context: ./dataStreamer
    ports:
      - 7474:7474
    restart: always
    networks:
      - default
  daily-aggregator:
    build:
      context: ./dailyAggregator
    links:
      - data-streamer
    environment:
      - DATA_STREAMER_ADDR=data-streamer
      - RABBITMQ_SERVER_ADDR=host.docker.internal
    restart: always
    networks:
      - default
  data-processing-service:
    build:
      context: ./dataProcessingService
    environment:
      - RABBITMQ_SERVER_ADDR=host.docker.internal
      - BRAZIL_API_ADDR=brazil-api
    links:
      - brazil-api
    ports:
      - 9090:9090
    restart: always
    networks:
      - default
  brazil-api:
    build:
      context: ./brazil-api
    ports:
      - 8080:8080
    restart: always
    networks:
      - default
networks:
  default:
