export const FETCH_STREAM_DATA_START = "FETCH_STREAM_DATA_START";
export const FETCH_STREAM_DATA_ARRIVED = "FETCH_STREAM_DATA_ARRIVED";

export const FETCH_STATE_POPULATION_START = "FETCH_STATE_POPULATION_START";
export const FETCH_STATE_POPULATION_SUCCESS = "FETCH_STATE_POPULATION_SUCCESS";
